# Generated by Django 2.0.2 on 2018-02-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='artist', verbose_name='프로필 이미지'),
        ),
        migrations.AddField(
            model_name='song',
            name='melon_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='멜론 Song ID'),
        ),
    ]
