# Generated by Django 2.0.2 on 2018-02-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20180220_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='song', verbose_name='프로필 이미지'),
        ),
    ]
