# Generated by Django 2.0.2 on 2018-02-08 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='장르'),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, verbose_name='가사'),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='곡 제목'),
            preserve_default=False,
        ),
    ]
