# Generated by Django 2.0.2 on 2018-02-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, max_length=20, verbose_name='Video ID')),
                ('channel_id', models.CharField(blank=True, max_length=50, verbose_name='Channel ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='제목')),
                ('channel_title', models.CharField(blank=True, max_length=20, verbose_name='채널')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('img_thumbnail', models.ImageField(blank=True, null=True, upload_to='youtube', verbose_name='썸네일')),
            ],
        ),
    ]
