# Generated by Django 2.0.2 on 2018-02-27 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtubes', '0001_initial'),
        ('artist', '0003_auto_20180226_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_youtube_artist_info_list', to='artist.Artist')),
                ('youtube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_youtube_info_list', to='youtubes.Youtube')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='like_youtube',
            field=models.ManyToManyField(blank=True, related_name='like_youtube', through='artist.YoutubeLike', to='youtubes.Youtube'),
        ),
        migrations.AlterUniqueTogether(
            name='youtubelike',
            unique_together={('artist', 'youtube')},
        ),
    ]
