# Generated by Django 2.0.2 on 2018-03-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_auto_20180228_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['-pk']},
        ),
    ]
